name: Generate terraform docs
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: examples/
        git-push: "true"
        output-format: markdown document
        output-file: USAGE.md
        output-method: replace
        args: --sensitive=false --hide requirements --required=false
        indention: 3
        config-file: .terraform-docs.yml